Fix "Read more on ..." text with X instead of Twitter
tsriram/astro-tweet pull request #15
Opened 2024-11-04 14:34 UTC by anotheri

A minor fix to follow the embed tweet design a bit closer

2024-12-30 11:57 UTC, tsriram requested changes
Hey @anotheri, sorry I totally missed notifications from this repo. Can we make it Astro 5.x instead of beta?

Edit: I applied the suggestion. Do you want to add changeset so that we can publish this as a new minor version?

2024-12-30 11:57 UTC, tsriram commented on packages/astro-tweet/package.json
> +    "astro": "^3.0.0 || ^4.0.0 || ^5.0.0-beta.1"
```suggestion
    "astro": "^3.0.0 || ^4.0.0 || ^5.0.0"
```

2025-01-09 21:24 UTC, anotheri commented
> Hey @anotheri, sorry I totally missed notifications from this repo. Can we make it Astro 5.x instead of beta?
> 
> Edit: I applied the suggestion. Do you want to add changeset so that we can publish this as a new minor version?

sure, looks good to me

2025-01-26 10:54 UTC, tsriram approved these changes

2025-01-26 10:54 UTC, merged